name: dinov2
channels:
  - xformers
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - antlr-python-runtime=4.9.3
  - aom=3.5.0
  - blas=2.16
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - cairo=1.16.0
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - colorama=0.4.6
  - cpython=3.9.20
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cuda-version=12.6
  - dataclasses=0.8
  - dav1d=1.2.1
  - expat=2.6.3
  - ffmpeg=6.0.0
  - filelock=3.16.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - fvcore=0.1.5.post20221221
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gnutls=3.7.9
  - graphite2=1.3.13
  - h2=4.1.0
  - harfbuzz=7.3.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - icu=72.1
  - idna=3.10
  - intel-openmp=2022.0.1
  - iopath=0.1.10
  - jinja2=3.1.4
  - jpeg=9e
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libass=0.17.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.11.1.6
  - libcurand=10.3.7.77
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.17
  - libdrm=2.4.123
  - libexpat=2.6.3
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.82.2
  - libgomp=14.2.0
  - libiconv=1.17
  - libidn2=2.3.7
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libnpp=11.7.4.75
  - libnsl=2.0.1
  - libnvjpeg=11.8.0.2
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.44
  - libsqlite=3.47.0
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libva=2.18.0
  - libvpx=1.13.1
  - libwebp-base=1.4.0
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libxml2=2.11.5
  - libzlib=1.3.1
  - markupsafe=3.0.2
  - mkl=2020.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.5
  - nettle=3.9.1
  - networkx=3.2.1
  - omegaconf=2.3.0
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=3.3.2
  - p11-kit=0.24.1
  - packaging=24.1
  - pcre2=10.44
  - pillow=9.4.0
  - pip=24.2
  - pixman=0.43.2
  - portalocker=2.10.1
  - pthread-stubs=0.4
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.9.20
  - python_abi=3.9
  - pytorch=2.0.0
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - setuptools=75.1.0
  - svt-av1=1.6.0
  - sympy=1.13.3
  - tabulate=0.9.0
  - termcolor=2.5.0
  - tk=8.6.13
  - torchmetrics=0.10.3
  - torchtriton=2.0.0
  - torchvision=0.15.0
  - tqdm=4.66.5
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - urllib3=2.2.3
  - wheel=0.44.0
  - x264=1!164.3095
  - x265=3.5
  - xformers=0.0.19
  - xorg-fixesproto=5.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yacs=0.1.8
  - yaml=0.2.5
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - cachetools==5.5.0
      - click==8.1.7
      - cloudpickle==3.1.0
      - cubinlinker-cu11==0.3.0.post2
      - cuda-python==11.8.3
      - cudf-cu11==24.8.3
      - cuml-cu11==24.8.0
      - cupy-cuda11x==13.3.0
      - dask==2024.7.1
      - dask-cuda==24.8.2
      - dask-cudf-cu11==24.8.3
      - dask-expr==1.1.9
      - distributed==2024.7.1
      - distributed-ucxx-cu11==0.39.1
      - fastrlock==0.8.2
      - fsspec==2024.10.0
      - importlib-metadata==8.5.0
      - joblib==1.4.2
      - libucx-cu11==1.15.0.post1
      - llvmlite==0.43.0
      - locket==1.0.0
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - msgpack==1.1.0
      - numba==0.60.0
      - numpy==1.26.4
      - nvtx==0.2.10
      - pandas==2.2.2
      - partd==1.4.2
      - psutil==6.1.0
      - ptxcompiler-cu11==0.8.1.post2
      - pyarrow==16.1.0
      - pygments==2.18.0
      - pylibraft-cu11==24.8.1
      - pynvml==11.4.1
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - raft-dask-cu11==24.8.1
      - rapids-dask-dependency==24.8.0
      - rich==13.9.3
      - rmm-cu11==24.8.2
      - scipy==1.13.1
      - six==1.16.0
      - sortedcontainers==2.4.0
      - submitit==1.5.2
      - tblib==3.0.0
      - toolz==1.0.0
      - tornado==6.4.1
      - treelite==4.3.0
      - tzdata==2024.2
      - ucx-py-cu11==0.39.2
      - ucxx-cu11==0.39.1
      - zict==3.0.0
      - zipp==3.20.2

